### PR TITLE
chore: go debugger setup

### PR DESCRIPTION
**Pull request by LucaHermann**
[Image from Gyazo](https://gyazo.com/1963d41bbdeebb3befe1ff272f3bc5f7)

### CODE REVIEW

**Comment by LucaHermann** [comment]
@Z-a-r-a-k-i i can't add you as a reviewer unfortunately

**Comment by Z-a-r-a-k-i** [comment]
> @Z-a-r-a-k-i i can't add you as a reviewer unfortunately

This is still work in progress, you should add WIP to the PR name

**Comment by Z-a-r-a-k-i** [comment]
LGTM

**Review by Z-a-r-a-k-i — APPROVED** [review]
LGTM

**Comment by LucaHermann** [comment]
[Image from Gyazo](https://gyazo.com/1963d41bbdeebb3befe1ff272f3bc5f7)

**Review by moul — APPROVED** [review]

**Pull request merged**
