### PR TITLE
feat: Creating nvmrc in web folder

### PR DESCRIPTION
**Pull request by lucasgdev**
Creating .nvmrc file in web folder to prevent node version issues.

### CODE REVIEW

**Comment by lucasgdev** [comment]
Netlify build is failing 'cause it was using another node version (10), we need to clean the cache and rebuild node modules to use node 12 (the one in the nvmrc), or we can stay with the version 10, and change the nvmrc file.

FYI: @moul @Z-a-r-a-k-i

**Comment by moul** [comment]
Ok let me clean the cache to try

**Comment by moul** [comment]
Also, note that you can specify a node version in the netlify.toml file: https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file

**Comment by lucasgdev** [comment]
> Also, note that you can specify a node version in the netlify.toml file: https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file

What do you think is better Manfred? I like the .nvmrc approach, because it helps to lock de version locally too.

**Comment by Z-a-r-a-k-i** [comment]
I like to use nmvrc file as well but it's bad practice to have the node version in two different files, it can create some issues in the future so can't we use only one of them ?

**Comment by lucasgdev** [comment]
> I like to use nmvrc file as well but it's bad practice to have the node version in two different files, it can create some issues in the future so can't we use only one of them ?

Yep @Z-a-r-a-k-i , right now we're not using node version inside the netlify config file, so .nvmrc would be the only source.

**Pull request merged**
