### PR TITLE
chore: added .git folder to dockerignore file

### PR DESCRIPTION
**Pull request by Z-a-r-a-k-i**

### CODE REVIEW

**Comment by moul** [comment]
by doing this, we lose some build context info i.e., https://github.com/pathwar/pathwar/blob/master/go/Makefile#L9

**Comment by Z-a-r-a-k-i** [comment]
> by doing this, we lose some build context info i.e., https://github.com/pathwar/pathwar/blob/master/go/Makefile#L9

Oohh I see, the issue is that it can bring a lot of data to the dockerfile and the COPY . . line will take more and more time, on my project, adding it reduced the dockerfile build time from 80sec

**Comment by moul** [comment]
the main issue with not ignore .git is mainly about the initial build context that docker requires before starting to run the steps

if you think that this specific step is slow -> https://github.com/pathwar/pathwar/blob/master/Dockerfile#L9
you can update it with more specific COPY, i.e, only the `go/` folder and maybe some other deps

**Comment by Z-a-r-a-k-i** [comment]
> the main issue with not ignore .git is mainly about the initial build context that docker requires before starting to run the steps
> 
> if you think that this specific step is slow -> https://github.com/pathwar/pathwar/blob/master/Dockerfile#L9
> you can update it with more specific COPY, i.e, only the `go/` folder and maybe some other deps

This line is only slowed down by the .git folder copy, all the rest takes 0,5sec I think it's the same for pathwar, but if it really needs to be in dockerfile, I guess 80sec on build time is nothing. Thanks for the clarifications

**Pull request closed without merging**
